OronaMVC/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Mvc;
using OronaMVC.DataAccess;
using OronaMVC.DataAccess.Repository.IRepository;
using OronaMVC.Models;

namespace OronaMVC.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
			IEnumerable<Company> objCompany = await _unitOfWork.Company.GetAllAsync();

			return View(objCompany);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Company obj)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.Company.AddAsync(obj);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Company created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var companyFromDb = await _unitOfWork.Company.GetFirstOrDefaultAsync(u => u.Id == id);
            if (companyFromDb == null)
            {
                return NotFound();
            }
            return View(companyFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Company obj)
        {
            if (ModelState.IsValid)
            {
                await _unitOfWork.Company.UpdateAsync(obj);
                await _unitOfWork.SaveAsync();
                TempData["success"] = "Company updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var companyFromDb = await _unitOfWork.Company.GetFirstOrDefaultAsync(u => u.Id == id);
            if (companyFromDb == null)
            {
                return NotFound();
            }

            return View(companyFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
            var obj = await _unitOfWork.Company.GetFirstOrDefaultAsync(u => u.Id == id);
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWork.Company.Remove(obj);
            await _unitOfWork.SaveAsync();
            TempData["success"] = "Company deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

OronaMVC/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OronaMVC.DataAccess.Repository.IRepository;
using OronaMVC.Models;
using OronaMVC.Models.ViewModels;
using OronaMVC.Utility;
using System.Security.Claims;

namespace OronaMVC.Web.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize]
    public class CartController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public ShoppingCartVM ShoppingCartVM { get; set; }

        public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = await _unitOfWork.ShoppingCart.GetAllShopCartBasedOnClaim(claim.Value),
                OrderHeader = new()
            };

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                cart.Price = cart.Product.Price;
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Count * cart.Price);
            }

            return View(ShoppingCartVM);
        }

        public async Task<IActionResult> Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM = new ShoppingCartVM()
            {
                ListCart = await _unitOfWork.ShoppingCart.GetAllShopCartBasedOnClaim(claim.Value),
                OrderHeader = new()
            };

            ShoppingCartVM.OrderHeader.ApplicationUser = await _unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(u => u.Id == claim.Value);

            ShoppingCartVM.OrderHeader.Name = ShoppingCartVM.OrderHeader.ApplicationUser.Name;
            ShoppingCartVM.OrderHeader.PhoneNumber = ShoppingCartVM.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartVM.OrderHeader.StreetAddress = ShoppingCartVM.OrderHeader.ApplicationUser.StreetAddress;
            ShoppingCartVM.OrderHeader.City = ShoppingCartVM.OrderHeader.ApplicationUser.City;
            ShoppingCartVM.OrderHeader.State = ShoppingCartVM.OrderHeader.ApplicationUser.State;
            ShoppingCartVM.OrderHeader.PostalCode = ShoppingCartVM.OrderHeader.ApplicationUser.PostalCode;

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                cart.Price = cart.Product.Price;
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Count * cart.Price);
            }

            return View(ShoppingCartVM);
        }

        [HttpPost]
        [ActionName("Summary")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SummaryPOST(ShoppingCartVM ShoppingCartVM)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartVM.ListCart = await _unitOfWork.ShoppingCart.GetAllShopCartBasedOnClaim(claim.Value);

            ShoppingCartVM.OrderHeader.OrderStatus = SD.StatusNew;
            ShoppingCartVM.OrderHeader.OrderDate = DateTime.Now;
            ShoppingCartVM.OrderHeader.ApplicationUserId = claim.Value;

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                cart.Price = cart.Product.Price;
                ShoppingCartVM.OrderHeader.OrderTotal += (cart.Count * cart.Price);
            }

            await _unitOfWork.OrderHeader.AddAsync(ShoppingCartVM.OrderHeader);
            await _unitOfWork.SaveAsync();

            foreach (var cart in ShoppingCartVM.ListCart)
            {
                OrderDetail orderDetail = new()
                {
                    ProductId = cart.ProductId,
                    OrderId = ShoppingCartVM.OrderHeader.Id,
                    Price = cart.Price,
                    Count = cart.Count
                };
                await _unitOfWork.OrderDetail.AddAsync(orderDetail);
                await _unitOfWork.SaveAsync();
            }

            _unitOfWork.ShoppingCart.RemoveRange(ShoppingCartVM.ListCart);
            await _unitOfWork.SaveAsync();

            return RedirectToAction("OrderConfirmation", new { ShoppingCartVM.OrderHeader.Id });
        }


        public IActionResult OrderConfirmation(int id)
        {
            return View(id);
        }

		public async Task<IActionResult> Plus(int cartId)
        {
            var cart = await _unitOfWork.ShoppingCart.GetFirstOrDefaultAsync(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.IncrementCount(cart, 1);
            await _unitOfWork.SaveAsync();
            return RedirectToAction(nameof(Index));
        }

		public async Task<IActionResult> Minus(int cartId)
		{
			var cart = await _unitOfWork.ShoppingCart.GetFirstOrDefaultAsync(u => u.Id == cartId);
            if(cart.Count <= 1)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
            }
            else
            {
				_unitOfWork.ShoppingCart.DecrementCount(cart, 1);
			}
			await _unitOfWork.SaveAsync();
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Remove(int cartId)
		{
			var cart = await _unitOfWork.ShoppingCart.GetFirstOrDefaultAsync(u => u.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cart);
			await _unitOfWork.SaveAsync();
			return RedirectToAction(nameof(Index));
		}
	}
}

OronaMVC/Controllers/CleaningTypeController.cs
using Microsoft.AspNetCore.Mvc;
using OronaMVC.DataAccess;
using OronaMVC.DataAccess.Repository.IRepository;
using OronaMVC.Models;

namespace OronaMVC.Controllers
{
    public class CleaningTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWOrk;

        public CleaningTypeController(IUnitOfWork unitOfWOrk)
        {
            _unitOfWOrk = unitOfWOrk;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<CleaningType> objCleaningType = await _unitOfWOrk.CleaningType.GetAllAsync();

            return View(objCleaningType);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CleaningType obj)
        {
            if(ModelState.IsValid)
            {
                var objFromDb = await _unitOfWOrk.CleaningType.GetFirstOrDefaultAsync(u => u.CleaningName == obj.CleaningName);
                if(objFromDb == null || objFromDb.CleaningName != obj.CleaningName)
                {
                    await _unitOfWOrk.CleaningType.AddAsync(obj);
                    await _unitOfWOrk.SaveAsync();
                    TempData["success"] = "Cleaning Type created successfully";
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("CleaningName", "Cleaning Type already exists.");
                }
                
            }
            return View(obj);
              
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var cleaningTypeFromDb = await _unitOfWOrk.CleaningType.GetFirstOrDefaultAsync(u => u.Id == id);
            if(cleaningTypeFromDb == null) 
            {
                return NotFound();
            }
            return View(cleaningTypeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CleaningType obj)
        {
			var objFromDb = await _unitOfWOrk.CleaningType.GetFirstOrDefaultAsync(u => u.CleaningName == obj.CleaningName);
			if (objFromDb == null || objFromDb.CleaningName != obj.CleaningName)
			{
				await _unitOfWOrk.CleaningType.UpdateAsync(obj);
				await _unitOfWOrk.SaveAsync();
                TempData["success"] = "Cleaning Type updated successfully";
                return RedirectToAction("Index");
			}
			else
			{
				ModelState.AddModelError("CleaningName", "Cleaning Type already exists.");
			}
			return View(obj);
		}

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var cleaningTypeFromDb = await _unitOfWOrk.CleaningType.GetFirstOrDefaultAsync(u => u.Id == id);
            if (cleaningTypeFromDb == null)
            {
                return NotFound();
            }

            return View(cleaningTypeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
            var obj = await _unitOfWOrk.CleaningType.GetFirstOrDefaultAsync(u => u.Id == id);  
            if (obj == null)
            {
                return NotFound();
            }

            _unitOfWOrk.CleaningType.Remove(obj);
            await _unitOfWOrk.SaveAsync();
            TempData["success"] = "Cleaning Type deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

OronaMVC/Controllers/WindowTypeController.cs
using Microsoft.AspNetCore.Mvc;
using OronaMVC.DataAccess;
using OronaMVC.DataAccess.Repository.IRepository;
using OronaMVC.Models;

namespace OronaMVC.Controllers
{
    public class WindowTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWOrk;
        private readonly IWebHostEnvironment _hostEnvironment;

        public WindowTypeController(IUnitOfWork unitOfWOrk, IWebHostEnvironment hostEnvironment)
        {
            _unitOfWOrk = unitOfWOrk;
            _hostEnvironment = hostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<WindowType> objWindowType = await _unitOfWOrk.WindowType.GetAllAsync();

            return View(objWindowType);
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            WindowType windowType = new();
            if(id == null || id == 0)
            {
                return View(windowType);
            }
            else
            {
                var objWindowTypeFromDb = await _unitOfWOrk.WindowType.GetFirstOrDefaultAsync(x => x.Id == id);
                return View(objWindowTypeFromDb);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(WindowType obj, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string wwwRootPath = _hostEnvironment.WebRootPath;
                if (file != null)
                {
                    string fileName = Guid.NewGuid().ToString();
                    var uploads = Path.Combine(wwwRootPath, @"images\windowTypes");
                    var extension = Path.GetExtension(file.FileName);

                    if (obj.ImageUrl != null)
                    {
                        var oldImagePath = Path.Combine(wwwRootPath, obj.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldImagePath))
                        {
                            System.IO.File.Delete(oldImagePath);
                        }
                    }

                    using (var fileStreams = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                    {
                        file.CopyTo(fileStreams);
                    }
                    obj.ImageUrl = @"\images\windowTypes\" + fileName + extension;
                }
                if (obj.Id == 0)
                {
                    await _unitOfWOrk.WindowType.AddAsync(obj);
                }
                else
                {
                    await _unitOfWOrk.WindowType.UpdateAsync(obj);
                }
                await _unitOfWOrk.SaveAsync();
                TempData["success"] = "Window Type created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var windowTypeFromDb = await _unitOfWOrk.WindowType.GetFirstOrDefaultAsync(u => u.Id == id);
            if (windowTypeFromDb == null)
            {
                return NotFound();
            }

            return View(windowTypeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePOST(int? id)
        {
            var obj = await _unitOfWOrk.WindowType.GetFirstOrDefaultAsync(u => u.Id == id);  
            if (obj == null)
            {
                return NotFound();
            }

            var oldImagePath = Path.Combine(_hostEnvironment.WebRootPath, obj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWOrk.WindowType.Remove(obj);
            await _unitOfWOrk.SaveAsync();
            TempData["success"] = "Window Type deleted successfully";
            return RedirectToAction("Index");
        }
    }
}

OronaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OronaMVC</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OronaMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OronaMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">CMS</a>
                            <div class="dropdown-menu" style="">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CleaningType" asp-action="Index">Cleaning Type</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="WindowType" asp-action="Index">Window Type</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Cart" asp-action="Index"><i class="bi bi-cart"></i></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="footer fixed-bottom text-white bg-primary">
        <div class="container">
            &copy; 2022 - OronaMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OronaMVC/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["error"]');
    </script>
}